version: "3.9"
services:
  vite:
    image: node:18
    working_dir: /data
    volumes:
      - ./src:/data
      - data_node_modules:/data/node_modules
    command: >
      bash -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5174"
    ports:
      - "5174:5174"

  app:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      # - ./src:/data
      - data_node_modules:/data/node_modules #追記　vite問題
    working_dir: /data
    command: php-fpm
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  data_node_modules: #追記　vite問題