name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uregular -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, memory_limit=2G
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist
          npm ci

      - name: Generate App Key & Migrate
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: laravel
          DB_PASSWORD: secret
        run: |
          php artisan key:generate
          php artisan migrate --force

      - name: Run PHPUnit
        run: vendor/bin/phpunit --fail-on-risky --fail-on-warning --color=always

      - name: Build Assets
        run: npm run build
